name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.dataStep.outputs.targets }}
    steps:
      - id: dataStep
        run: |
          TARGETS=$(echo '["dev", "qa", "prod"]')
          echo "$(jq -cn --argjson environments "$TARGETS" '{targets: $environments}')" >> $GITHUB_OUTPUT
  run-matrix:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{ fromJson(needs.setup.outputs.targets) }}
    steps:
      - run: echo ${{matrix.target}}