# This is a basic workflow to help you get started with Actions
name: Publish

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_run:
    workflows:
      - CI
    branches: main
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dataStep.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./gradlew build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: build/
          if-no-files-found: error
